import { SeoLandingPage } from "@/components/marketing/SeoLandingPage";
import { buildMetadata } from "@/lib/seo";

export const metadata = buildMetadata({
  title: "AI Detector | NexusDesk",
  description:
    "Check text with the NexusDesk AI Detector. Review AI-like writing patterns, highlight suspicious passages, and inspect content before publishing.",
  path: "/ai-detector",
  keywords: ["AI detector", "AI content detector", "detect AI writing", "AI text checker"],
  robots: {
    index: true,
    follow: true,
  },
});

export default function AiDetectorPage() {
  return (
    <SeoLandingPage
      eyebrow="AI Detector"
      title="AI Detector for checking AI-like writing patterns"
      intro="NexusDesk AI Detector helps you review text for machine-like phrasing and suspicious patterns. It is built for users who want a second pass before submitting, publishing, or revising content."
      paragraphs={[
        "People searching for an AI detector usually want fast feedback on whether text reads like it was generated by a model. NexusDesk gives them a public page that explains the detector clearly and an immediate path into the actual detector interface.",
        "The detector workflow is useful for drafts, essays, articles, and other written content where readers may care about tone, authorship signals, or passages that feel over-optimized. The page also adds more crawlable HTML than the tool workspace alone, which helps search engines understand the feature.",
        "If your goal is to detect AI writing, review flagged sections, and then refine the result, this page pairs naturally with the NexusDesk Humanizer and note workflows linked below.",
      ]}
      ctaHref="/chat?mode=detector"
      ctaLabel="Open AI Detector"
      secondaryHref="/humanizer"
      secondaryLabel="See AI Humanizer"
      highlights={[
        "Built for AI text review and suspicious-pattern checking.",
        "Useful before submitting essays, reports, or web copy.",
        "Connects naturally to follow-up rewriting and study workflows.",
      ]}
      relatedLinks={[
        { href: "/humanizer", label: "AI Humanizer landing page" },
        { href: "/ai-note", label: "AI Note landing page" },
        { href: "/ai-study", label: "AI Study landing page" },
        { href: "/converter", label: "Converter workspace" },
      ]}
      faq={[
        {
          question: "What kind of content can I check?",
          answer: "You can review essays, articles, outlines, reports, and other pasted text where you want to inspect AI-like writing signals.",
        },
        {
          question: "Does this page open the real detector?",
          answer: "Yes. The call to action links into the NexusDesk workspace with the detector mode selected so users land on the right tool.",
        },
      ]}
    />
  );
}
